### ISSUE TITLE
Request: Tidal support

### ISSUE THREAD

**Issue by Dyras** [guihkx/spotishush#23] opened 2022-04-28 14:23 UTC
Hello! Would it be possible to get support for Tidal too? They have better audio quality than Spotify and Deezer, even on the free (America-only) tier.

Pretty please? <3

**Comment by guihkx** [comment] 2022-05-01 01:45
Released in v2022.4.30, please give it a go and report back if you find any problems :)

**Comment by Dyras** [comment] 2022-05-01 12:49
Girls will surely send you wedding proposals for this. Thanks! Gonna go try it now, will report back.

**Comment by Dyras** [comment] 2022-05-03 17:56
@guihkx 
So after trying it today (The Chrome store was slow to send me the update) I can report back that the song sometimes isn't unmuted properly after the ad is done playing

It doesn't seem to happen ever if you set a song to loop

It does however happen if you manually switch songs. Trying to figure out exactly what triggers it!

**Comment by guihkx** [comment] 2022-05-03 18:12
Thanks for testing, I'll try to take a look at this later today.

**Comment by Dyras** [comment] 2022-05-03 18:20
It happened again just now. Here's an overly detailed explanation for what I did:

1. Listen to some songs on my liked list
2. Switch to a mix, an ad plays the first thing that happens
3. Minimize Edge and read the news
4. Wonder where the music went and open Edge and see it's muted

**Comment by guihkx** [comment] 2022-05-04 12:01
Last night I left Edge playing songs for about 3 hours straight but I still couldn't reproduce this problem :(

When it happens again, can you please leave the tab muted, open the Developer console  (Ctrl Shift I) and screenshot the Console tab for me? Like this:

![image](https://user-images.githubusercontent.com/626206/166677308-fc3fa2d4-3581-4452-a5b5-9a5b0f630271.png)


Thanks

**Comment by Dyras** [comment] 2022-05-04 19:32
Of course, will screenshot it the next time it happens :)

I find that it **doesn't** happen when it's playing constantly. It happens when you manually switch songs.

**Comment by guihkx** [comment] 2022-05-04 20:12
I see... When you say switching songs you mean by pressing the "next" button? Or picking a song on a different playlist/album and playing that? Maybe both?

**Comment by Dyras** [comment] 2022-05-05 07:54
It happens when I pick a different song in a different playlist or album, from what I've noticed

**Comment by Dyras** [comment] 2022-05-08 12:13
It happened again. I went for a walk and I left the music on, and when I came home a song is muted.

![image](https://user-images.githubusercontent.com/12563436/167295514-c1e60f46-8116-4e50-a6ba-b7302165f0c7.png)

I waited for another ad to play, but it doesn't unmute after that either.

I'm using Edge with "Added security" if that matters
![image](https://user-images.githubusercontent.com/12563436/167295499-803a8d1b-75fd-4683-967f-f4968cbb194e.png)

**Comment by guihkx** [comment] 2022-05-08 13:39
That's very helpful, thank you. I have been working on a different ad detection approach for TIDAL.

I'll try to publish it today. Last time it took you too long to get the update because SpotiShush got stuck on Google's new review process, but this time it should be faster. I'll let you know when I publish it.

**Comment by guihkx** [comment] 2022-05-10 14:10
v2022.5.9 is now published on the Chrome Webstore. Please test it.

Thanks

**Comment by guihkx** [comment] 2022-05-12 17:05
Oof :(

Can you also enable timestamps so I can have a notion of how fast this can happen. This is how you enable timestamps:

![Peek 2022-05-12 14-05](https://user-images.githubusercontent.com/626206/168130135-cfa46340-1f0f-4c6c-b8d4-ef6300210f49.gif)

**Comment by Dyras** [comment] 2022-05-12 17:26
Timestamps now enabled! Will report back again when it happens next time.

I typically listen to music at work during Mondays to Thursdays so that's when it's the most likely to happen for me. It happens on my personal computer at home as well, but it's less likely since I listen to it less.

I started working around 2:30 hours before I posted the last message, but it typically takes longer than that to happen.

**Comment by guihkx** [comment] 2022-05-12 20:17
Thank you! If possible, in your next screenshot, please include the TIDAL website as well (including the tab indicator), like this:

![Screenshot from 2022-05-12 17-16-21](https://user-images.githubusercontent.com/626206/168160720-678cc6c5-d862-4b78-924e-aa662e7fcc1e.png)


SpotiShush detects ads by monitoring specific HTML elements, so I just want to make sure things are not visually off in that regard...

**Comment by Dyras** [comment] 2022-05-15 07:06
Hello again, I will make sure to add a screenshot the next time it happens :) 

It might take some time though :D 

![image](https://user-images.githubusercontent.com/12563436/168461421-afb444bd-3c23-4e37-b49c-0d4942ff1961.png)

**Comment by guihkx** [comment] 2022-05-15 18:34
Haha I was trying to reproduce this too and I just that error :S

I'll create another account

**Comment by Dyras** [comment] 2022-06-07 14:49
As requested!

![image](https://user-images.githubusercontent.com/12563436/172410813-b933d8a3-a378-4b62-8b87-c9776de836c7.png)
![image](https://user-images.githubusercontent.com/12563436/172410882-920235cd-bc88-4154-b1f0-0eaafe169d49.png)

**Comment by Dyras** [comment] 2022-06-08 17:12
And again today. Do you want me to try Brave to see if I can replicate it with that browser as well?
![image](https://user-images.githubusercontent.com/12563436/172676879-d173b4b5-9058-4133-989c-8850b24a8932.png)

**Comment by guihkx** [comment] 2022-06-09 19:51
I don't think that's necessary, they both share the same engine so it probably affects all Chromium-based browsers. I still can't reproduce this locally, but judging from your screenshots everything looks normal. If I had to guess what the problem is, I'd say that at some point this element we're observing for mutations, gets removed:

https://github.com/guihkx/spotishush/blob/b9691d296f25c1df8d0b00a588200bab1e16c50d/src/spotishush.js#L114

It should be an easy fix, but I just want to make sure that's the actual issue.

Thanks for the help so far!

**Comment by Dyras** [comment] 2022-06-09 20:52
No problem man. I wonder why it never happens for you? It happens on two different computers for me, one is a budget company laptop and one is a not-so-budget gaming desktop, so there's nothing in common aside from me living in the same country on both computers (duh!)

Thanks for the great work!

**Comment by guihkx** [comment] 2022-06-10 04:21
No clue either :(

Nevertheless I'll continue trying to reproduce it anyway, I'm sure I'll hit this issue at some point

**Comment by guihkx** [comment] 2022-06-23 21:12
Let's hope that's the case! Nevertheless I'll leave this open for some more time.

**Closed** 2022-07-11 14:52 UTC
